### ISSUE TITLE
Update steps as stated in READ.ME file errors when executing.

### ISSUE THREAD

**Issue by tokio69** [DecentralizedAmateurPagingNetwork/Web#168] opened 2018-05-30 09:28 UTC
When I try  to update the web version from 2.1.3 to 2.2.5 On ythe first step I get an error.
Is this file up to date on all steps to be taken and with correct comands?

**Comment by MarvinMenzerath** [comment] 2018-05-30 09:50
There is nothing wrong with the upgrade-guide.
It would be interesting to know what kind of error message you get. This is probably related to some kind of customizations you made.

Alternatively you can always backup your configuration-files and start with a fresh clone of the repository.

**Comment by tokio69** [comment] 2018-05-30 09:55
I started a ticket for this issue also on osTicket.
The error is this one when I do git fetch (Step 1 on the guide) :

fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

Van: Marvin Menzerath <notifications@github.com>
Verzonden: woensdag 30 mei 2018 11:51
Aan: DecentralizedAmateurPagingNetwork/Web <Web@noreply.github.com>
CC: Tom Knockaert <tom@tokiogroup.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DecentralizedAmateurPagingNetwork/Web] Update steps as stated in READ.ME file errors when executing. (#168)


There is nothing wrong with the upgrade-guide.
It would be interesting to know what kind of error message you get. This is probably related to some kind of customizations you made.

Alternatively you can always backup your configuration-files and start with a fresh clone of the repository.

**Comment by tokio69** [comment] 2018-05-30 12:45
OK, That worked so I could get past the first step.
Second one is “Run through step 2 of the installation process” so I do git checkout tags/v2.0.0
I get this response : “HEAD is now at 2ced8ef... v2.0.0” (maybe this should have some appendix stating that you have to change that to the latest version like 2.2.5, Since I have 2.1.3 installed I used the tag for 2.1.6 as it is the latest )
I go to step 3 “Run through steps 8. to 11. of the installation process” the first one is “npm install”
I do that and it seems to go trough after about 40 seconds I get some errors :  “No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a …”
When this is done I get this error :
ERROR  Failed to compile with 3 errors                                                                                                                                                                   2:36:03 PM
These relative modules were not found:
* ./defaultMap.json in ./src/store/index.js
* ./defaultText.json in ./src/store/index.js
* ./defaultUrls.json in ./src/store/index.js
These are the files the NEW installation installer is talking about in Step 3. But since in the update steps these are not needed to do ?



Van: Marvin Menzerath <notifications@github.com>
Verzonden: woensdag 30 mei 2018 13:23
Aan: DecentralizedAmateurPagingNetwork/Web <Web@noreply.github.com>
CC: Tom Knockaert <tom@tokiogroup.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DecentralizedAmateurPagingNetwork/Web] Update steps as stated in READ.ME file errors when executing. (#168)


It seems like you didn't use git clone to initially download the repository. You can try to add the remote repository using git remote add origin https://github.com/DecentralizedAmateurPagingNetwork/Web.git and re-run the git fetch.
If this is not successful, you should start with a fresh clone of the repository and copy your configuration files.

**Comment by MarvinMenzerath** [comment] 2018-05-30 14:00
Regarding step 2: good idea, will change this in a bit. You should always use the latest tag, in this case `v2.2.5`.

The warning you see while running `npm install` is created by one of the dependencies. This will be fixed soon by updating those.

The errors you get regarding the `defaultXXX.json` files are caused by the fact that those files are simply missing. If you followed the installation guide previously you should already have those files. If not, just create them by following steps 3, 4 and 5. You may also need to follow step 6 and 7 in this case.

**Comment by tokio69** [comment] 2018-06-01 08:45
Hello Marvin,
I still get the same error.
ERROR  Failed to compile with 3 errors                                                                                                                                                                                        10:40:05 AM

These relative modules were not found:

* ./defaultMap.json in ./src/store/index.js
* ./defaultText.json in ./src/store/index.js
* ./defaultUrls.json in ./src/store/index.js

But when I look in my src folder they are there and with correct settings, full path is /opt/dapnet/Web/src/store/
I have the .example and the .json files in it. http://portal.hampager.be. It now works in 2.1.3 or do I have to re-copy them again and make adjustments there?

Tom

Van: Marvin Menzerath <notifications@github.com>
Verzonden: woensdag 30 mei 2018 16:01
Aan: DecentralizedAmateurPagingNetwork/Web <Web@noreply.github.com>
CC: Tom Knockaert <tom@tokiogroup.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DecentralizedAmateurPagingNetwork/Web] Update steps as stated in READ.ME file errors when executing. (#168)


Regarding step 2: good idea, will change this in a bit. You should always use the latest tag, in this case v2.2.5.

The warning you see while running npm install is created by one of the dependencies. This will be fixed soon by updating those.

The errors you get regarding the defaultXXX.json files are caused by the fact that those files are simply missing. If you followed the installation guide previously you should already have those files. If not, just create them by following steps 3, 4 and 5. You may also need to follow step 6 and 7 in this case.

**Comment by MarvinMenzerath** [comment] 2018-06-04 08:38
Since `v2.1.1` the build-script recognizes a missing `defaultXXX.json` file and you shouldn't even see this kind of error-message, so I'm not sure why you are still getting this error.

The default files haven't changed since a few releases, so you can copy them.

**Comment by dh3wr** [comment] 2018-06-19 08:06
I did the update on the VM right now in /opt/dapnet/Web to branch development and it worked all well. I also replied to Tom on osTicket. So I hope this issue is solved. If not, open again.

**Closed by dh3wr** 2018-06-19 08:06 UTC
Labels: question, waiting

**Comment by tokio69** [comment] 2018-06-19 16:02
Hello Ralf,
The Node ON3DHC is no longer working now. My transmitters cannot connecto to it.
Also the layout of portal.hampager.be is very small now. Maybe not everything is properly configured?
Tom

Van: Ralf Wilke DH3WR <notifications@github.com>
Verzonden: dinsdag 19 juni 2018 10:07
Aan: DecentralizedAmateurPagingNetwork/Web <Web@noreply.github.com>
CC: Tom Knockaert <tom@tokiogroup.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DecentralizedAmateurPagingNetwork/Web] Update steps as stated in READ.ME file errors when executing. (#168)


Closed #168<https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/168>.

**Comment by tokio69** [comment] 2018-06-19 16:03
ERROR 16:02:35 Connection failed.
INFO 16:02:25 Connection to on3dhc.db0sda.ampr.org:43434...
WARN 16:02:25 Connecting to next fallback server...
ERROR 16:02:20 Connection failed.
INFO 16:02:16 Connection to dapnet.hampager.be:43434...
ERROR 16:02:12 Connection failed.
INFO 16:02:11 Connection to dapnet.ampr.org:43434...
WARN 16:02:11 Connecting to next fallback server...
ERROR 16:02:06 Connection failed.
INFO 16:02:06 Connection to dapnet.hampager.be:43434...


Van: Ralf Wilke DH3WR <notifications@github.com>
Verzonden: dinsdag 19 juni 2018 10:07
Aan: DecentralizedAmateurPagingNetwork/Web <Web@noreply.github.com>
CC: Tom Knockaert <tom@tokiogroup.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DecentralizedAmateurPagingNetwork/Web] Update steps as stated in READ.ME file errors when executing. (#168)


Closed #168<https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/168>.

**Comment by dh3wr** [comment] 2018-06-20 10:01
Hi Tom,
What do you mean by "layout very small"? This is how it's displayed on my browser:
![grafik](https://user-images.githubusercontent.com/16710361/41650664-ecbc2928-747e-11e8-8b0d-24c5edc86254.png)

I just updated the website to newest version 2.2.7.

The Node is runnig again, too. It's a known problem of the cluster breaking into parts, but with https://github.com/DecentralizedAmateurPagingNetwork/core-ng this will be gone.

**Comment by tokio69** [comment] 2018-06-20 14:57
No attachement but that is fine, it is version 2.2.6 now.
The banner is very big on top compared to the rest of the text.
But all that is fine, prior is the Orange Pi support now.
Tom

Van: Ralf Wilke DH3WR <notifications@github.com>
Verzonden: woensdag 20 juni 2018 12:02
Aan: DecentralizedAmateurPagingNetwork/Web <Web@noreply.github.com>
CC: Tom Knockaert <tom@tokiogroup.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DecentralizedAmateurPagingNetwork/Web] Update steps as stated in READ.ME file errors when executing. (#168)


Hi Tom,
What do you mean by "layout very small"? This is how it's displayed on my browser:
[grafik]<https://user-images.githubusercontent.com/16710361/41650664-ecbc2928-747e-11e8-8b0d-24c5edc86254.png>

I just updated the website to newest version 2.2.7.

The Node is runnig again, too. It's a known problem of the cluster breaking into parts, but with https://github.com/DecentralizedAmateurPagingNetwork/core-ng this will be gone.

**Comment by dh3wr** [comment] 2018-06-20 21:11
If you look on github you will see the attachment.
https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/168#issuecomment-398781766
OrangePi is sent to DL2IC for improvment

**Comment by tokio69** [comment] 2018-06-21 14:49
The node is again offline.
How can I prevent this?
ERROR 14:48:28 Connection failed.
INFO 14:48:28 Connection to dapnet.hampager.be:43434...
ERROR 14:48:23 Connection failed.
INFO 14:48:13 Connection to dapnet.db0sda.ampr.org:43434...
WARN 14:48:13 Connecting to next fallback server...
ERROR 14:48:08


Van: Ralf Wilke DH3WR <notifications@github.com>
Verzonden: woensdag 20 juni 2018 23:12
Aan: DecentralizedAmateurPagingNetwork/Web <Web@noreply.github.com>
CC: Tom Knockaert <tom@tokiogroup.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DecentralizedAmateurPagingNetwork/Web] Update steps as stated in READ.ME file errors when executing. (#168)


If you look on github you will see the attachment.
#168 (comment)<https://github.com/DecentralizedAmateurPagingNetwork/Web/issues/168#issuecomment-398781766>
OrangePi is sent to DL2IC for improvment

**Comment by tokio69** [comment] 2018-06-21 17:21
Ok thank you, if he needs a standard installed OPi I can have one setup and open the needed ports to see and test.
